language: node_js
node_js: lts/*
install:
- yarn install
before_script:
- yarn global add firebase-tools
script:
- yarn build
- yarn test
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email: false