language: node_js
node_js: lts/*
install:
- yarn install
script:
- yarn build
- yarn test
deploy:
  provider: firebase
  token:
    secure: ITPFFOWJ1g/YVJUyvj1KtgKBMfJUtz3y9jzbeUyK92YJK4RhnlSv7aw7WxrT6PfP00s0gr/64EwyB0TmKMUfw6nwb6h78ZfN5doYfKNNRQxL67BD7j3dgyihdJL9JcS5KsW02iPFxIo9q/2P4bKWePPj5fRsYOXpMpxqzA7whWp7yGImVmTKQu17OhuAU1moHpaUOOyl2OELg8nbikFTrt8MguUZcp723QcVa4xoGx664C5IncnHfuNymF/vkBOeAvdw2tP8sXp41FBctLaYS8qer3cXWG2Uwwcld5qNfVOu3IUTtCTtDMh6M9ooXI3uy/ExFJc6t3xmcG2Ddt25744a/fniZvPE3g4AJ1aLTej9BweN+2v1QiIzCHfBU+FrYGXRbJXs3uNDck3aMHrRvUuQ6gaF1VRvARZIZJj2hjjDGIYsUB2vbdBSMmaEtrAF5oukowTWa0nbuekabbc7c2qlPWYVHYkhQwyUmOZEjjma0rSrWtQBs0fPD5IoSuUsVDEyR8SkmQVXQDJpc0YIauZrGa2Hus1ZnNFqKd8Ym2xiJNjSOXP1lwPZoM88bkJGfsXNDy9T7C1jG2Ts2+EgzX/R8vZZeIitEMI+Slmh6aQpkTZbRzefYRXN7WuCRnfiiWm0cELzU3qHbv0KQWv/nxjT0JlJNZk+vSSUPkO+J4s=
